# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yamltest}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gaspard Bucher"]
  s.date = %q{2010-05-13}
  s.description = %q{yamltest lets you configure unit test with yaml documents}
  s.email = %q{gaspard@teti.ch}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "lib/yamltest.rb",
     "lib/yamltest/version.rb",
     "test/gem_test/foo.yml",
     "test/gem_test/simple_test.rb",
     "test/test_helper.rb",
     "test/yamltest/simple.yml",
     "test/yamltest_test.rb",
     "test/zoo/complicated.yml",
     "yamltest.gemspec"
  ]
  s.homepage = %q{http://github.com/zena/yamltest/tree}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{yamltest lets you configure unit test with yaml documents}
  s.test_files = [
    "test/gem_test/simple_test.rb",
     "test/test_helper.rb",
     "test/yamltest_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

