# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "yamltest"
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gaspard Bucher"]
  s.date = "2012-10-29"
  s.description = "yamltest lets you configure unit test with yaml documents"
  s.email = "gaspard@teti.ch"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "Manifest.txt",
    "README.rdoc",
    "Rakefile",
    "lib/yamltest.rb",
    "lib/yamltest/version.rb",
    "test/gem_test/foo.yml",
    "test/gem_test/simple_test.rb",
    "test/test_helper.rb",
    "test/yamltest/other_folder/bar.yml",
    "test/yamltest/simple.yml",
    "test/yamltest_test.rb",
    "test/zoo/complicated.yml",
    "yamltest.gemspec"
  ]
  s.homepage = "http://github.com/zena/yamltest/tree"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "yamltest lets you configure unit test with yaml documents"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

